CREATE DATABASE DesafioDevBackEndIII
GO

CREATE TABLE TB_CLIENTE (
	ID_CLIENTE UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	NM_CLIENTE VARCHAR(30) NOT NULL,
	NU_CPF VARCHAR(11) NOT NULL,
	NU_IDADE VARCHAR(2) NOT NULL)
GO

CREATE TABLE TB_ENDERECO (
	ID_ENDERECO UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	NM_LOGRADOURO VARCHAR(50) NOT NULL,
	NM_BAIRRO VARCHAR(40) NOT NULL,
	NM_CIDADE VARCHAR(40) NOT NULL,	
	NM_ESTADO VARCHAR(40) NOT NULL,
	CD_CLIENTE UNIQUEIDENTIFIER)
GO

ALTER TABLE TB_ENDERECO
ADD CONSTRAINT FK_Cliente_ENDERECO
FOREIGN KEY (CD_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE);
GO